$:
  vscode:
    - docker:
        image: docker.cnb.cool/iiistudio/os/docker/python:3.12.11
      services:
        - vscode
        - docker
main:
  web_trigger:
    - runner:
        cpus: 1
      stages:
        - name: 测回
          script: |
            git reset --hard ${commit}
            git push -f origin main